### ISSUE TITLE
GPX tracks from Parque Amate

### ISSUE THREAD

**Issue by moiarcsan** [GeoinquietosSevilla/recursos#2]
Talk to Antonio Laguna to get the gpx tracks from Parque Amate and commit to github repo

**Comment by Delawen** [comment]
Supongo que no contestaron...

**Comment by moiarcsan** [comment]
Nos enviaron un documento del que se pueden extraer las trazas gpx.
Estoy procesándolo para subirlo.

**Comment by lacasavacia** [comment]
Ok, voy atrasada con los deberes, retomo tareas y estoy pendiente

**Comment by moiarcsan** [comment]
Tendríamos que buscar la opción de ver si podemos obtener las trazas reales de la app, sino intentar replicarla en cartoDB lo mejor posible.

**Comment by lacasavacia** [comment]
Ok
