### ISSUE TITLE
Obtener trazas GPX de Sevilla Patina

### ISSUE THREAD

**Issue by moiarcsan** [GeoinquietosSevilla/recursos#3]
Tarea para gestionar la recuperación de las trazas gpx que realizó el grupo Sevilla Patina durante la mañana de la Mapping Party.

**Comment by lacasavacia** [comment]
Obtenidas, ahora sólo tengo que averiguar cómo subirlas...

**Comment by lacasavacia** [comment]
...

**Comment by lacasavacia** [comment]
...
